
# districts = ['ALIRAJPUR', 'DEWAS', 'SEONI', 'JABALPUR', 'INDORE', 'CHHATARPUR', 'SATNA', 'MANDLA', 'SHIVPURI', 'KHARGONE', 'NEEMUCH', 'ANUPPUR', 'VIDISHA', 
#     'CHHINDWARA', 'BURHANPUR', 'SIDHI', 'BALAGHAT', 'AGAR MALWA', 'MAIHAR', 'SINGRAULI', 'KATNI', 'KHANDWA', 'MANDSAUR', 'PANNA', 'DHAR', 'GUNA', 'GWALIOR', 
#     'DINDORI', 'SHEOPUR', 'DAMOH', 'DATIA', 'REWA', 'NARSINGHPUR', 'SAGAR', 'SHAJAPUR', 'UJJAIN', 'BETUL', 'BARWANI', 'MAUGANJ', 'HOSHANGABAD', 'RAISEN', 
#     'TIKAMGARH', 'SHAHDOL', 'UMARIA', 'RAJGARH', 'ASHOKNAGAR', 'NIWARI', 'JHABUA', 'BHOPAL', 'MORENA', 'PANDHURNA', 'SEHORE', 'BHIND', 'HARDA', 'RATLAM']


# blocks = [
#     "AGAR", "AJAIGARH", "ALIRAJPUR", "ALOT", "AMARPATAN", "AMARPUR", "AMARWARA",
#     "AMBAH", "AMLA", "ANUPPUR", "ARON", "ASHOKNAGAR", "ASHTA", "ATER", "ATHNER",
#     "BABAI", "BADA MALHERA", "BADARWAS", "BADI", "BADNAGAR", "BADNAWAR", "BADOD",
#     "BADWAH", "BADWARA", "BAGH", "BAGLI", "BAHORIBAND", "BAIHAR", "BAJAG", "BAJNA",
#     "BALADI", "BALAGHAT", "BALDEOGARH", "BAMORI", "BANDA", "BANKHEDI", "BARGHAT",
#     "BARGI", "BARWANI", "BASODA", "BATIAGARH", "BEGAMGANJ", "BEOHARI", "BERASIA",
#     "BETUL", "BHABRA", "BHAGWANPURA", "BHAINSDEHI", "BHANDER", "BHANPURA",
#     "BHIKANGAON", "BHIMPUR", "BHIND", "BHITARWAR", "BHOPAL URBAN", "BIAORA",
#     "BICHHIYA", "BICHHUA", "BIJADANDI", "BIJAWAR", "BINA", "BIRSA", "BUDNI",
#     "BURHANPUR", "BURHAR", "BUXWAHA", "CHACHODA", "CHANDERI", "CHAURAI",
#     "CHAWARPATHA", "CHHAIGAON MAKHAN", "CHHAPARA", "CHHATARPUR", "CHHINDWARA",
#     "CHICHLI", "CHICHOLI", "CHITRANGI", "DABRA", "DAHI", "DAMOH", "DATIA", "DEORI",
#     "DEOSAR", "DEPALPUR", "DEWAS", "DHANORA", "DHAR", "DHARMPURI", "DHIMAR KHEDA",
#     "DINDORI", "GAIRATGANJ", "GANDHWANI", "GANGEV", "GAROTH", "GAURIHAR", "GHANSOR",
#     "GHATIA", "GHATIGAON", "GHODA DONGRI", "GHUGHRI", "GOGAON", "GOHAD", "GOHPARU",
#     "GOTEGAON", "GUNA", "GUNNOR", "GWALIOR URBAN", "GYARASPUR", "HANUMANA", "HARDA",
#     "HARRAI", "HARSUD", "HATTA", "HOSHANGABAD", "ICHHAWAR", "INDORE", "INDORE URBAN",
#     "ISAGARH", "JABALPUR URBAN", "JABERA", "JAISINAGAR", "JAISINGHNAGAR", "JAITHARI",
#     "JAMAI", "JAORA", "JATARA", "JAURA", "JAWA", "JAWAD", "JHABUA", "JHIRNIYA",
#     "JIRAPUR", "JOBAT", "KAILARAS", "KALAPIPAL", "KANNOD", "KARAHAL", "KARANJIYA",
#     "KARELI", "KARERA", "KARKELI", "KASRAWAD", "KATANGI", "KATTHIWARA", "KEOLARI",
#     "KESLA", "KESLI", "KHAIRLANJI", "KHAKNAR", "KHALWA", "KHANDWA", "KHANIYADHANA",
#     "KHARGONE", "KHATEGAON", "KHCHROD", "KHILCHIPUR", "KHIRKIYA", "KHURAI", "KIRNAPUR",
#     "KOLARAS", "KOTMA", "KUKSHI", "KUNDAM", "KURAI", "KURWAI", "KUSMI", "LAHAR",
#     "LAKHNADON", "LALBARRA", "LANJI", "LATERI", "LAUNDI", "MAHESHWAR", "MAHIDPUR",
#     "MAIHAR", "MAJHAULI", "MAJHGAWAN", "MAJHOLI", "MALHARGARH", "MALTHONE", "MANASA",
#     "MANAWAR", "MANDLA", "MANDSAUR", "MANPUR", "MAUGANJ", "MAWAI", "MEGHNAGAR",
#     "MEHGAON", "MENHADWANI", "MHOW", "MOHGAON", "MOHKHED", "MOMAN BADODIYA", "MORAR",
#     "MORENA", "MULTAI", "MUNGAOLI", "MURWARA", "NAGOD", "NAIGARHI", "NAINPUR",
#     "NALCHHA", "NALKHEDA", "NARAYANGANJ", "NARSINGHGARH", "NARSINGHPUR", "NARWAR",
#     "NASRULLAGANJ", "NATERAN", "NEEMUCH", "NISARPUR", "NIWALI", "NIWARI", "NIWAS",
#     "NOWGONG", "OBEDULLAGANJ", "PAHADGARH", "PALERA", "PALI", "PANAGAR", "PANDHANA",
#     "PANDHURNA", "PANNA", "PANSEMAL", "PARASIA", "PARASWADA", "PATAN", "PATERA",
#     "PATHARIA", "PATI", "PAWAI", "PETLAWAD", "PHANDA", "PICHHORE", "PIPARIYA",
#     "PIPLODA", "POHARI", "PORSA", "PRABHAT PATTAN", "PRITHVIPUR", "PUNASA",
#     "PUSHPARAJGARH", "RAGHOGARH", "RAHATGARH", "RAIPUR KARCHULIYAN", "RAJGARH",
#     "RAJNAGAR", "RAJPUR", "RAMA", "RAMNAGAR", "RAMPUR NAIKIN", "RAMPUR-BAGHELAN",
#     "RANAPUR", "RATLAM", "REHLI", "REWA", "RITHI", "RON", "SABALGARH", "SAGAR",
#     "SAIKHEDA", "SAILANA", "SAMNAPUR", "SANCHI", "SANWER", "SARANGPUR", "SARDARPUR",
#     "SAUSAR", "SEGAON", "SEHORE", "SENDHWA", "SEONDHA", "SEONI", "SEONI MALWA",
#     "SHAHGARH", "SHAHNAGAR", "SHAHPUR", "SHAHPURA", "SHAHPURA", "SHAJAPUR", "SHEOPUR",
#     "SHIVPURI", "SHUJALPUR", "SIDHI", "SIHAWAL", "SIHORA", "SILWANI", "SIRMOUR",
#     "SIRONJ", "SITAMAU", "SOHAGPUR", "SOHAGPUR", "SOHAWAL", "SONDWA", "SONKATCH",
#     "SUSNER", "TAMIA", "TARANA", "TENDUKHEDA", "TEONTHAR", "THANDLA", "THIKRI",
#     "TIKAMGARH", "TIMARNI", "TIRLA", "TONKHURD", "UDAIGARH", "UDAIPURA", "UJJAIN",
#     "UMARBAN", "UNCHEHARA", "VIDISHA", "VIJAYPUR", "VIJAYRAGHAVGARH", "WAIDHAN",
#     "WARASEONI"
# ]

districts = ['alirajpur', 'dewas', 'seoni', 'jabalpur', 'indore', 'chhatarpur', 'satna', 
    'mandla', 'shivpuri', 'khargone', 'neemuch', 'anuppur', 'vidisha', 'chhindwara', 'burhanpur',
    'sidhi', 'balaghat', 'agar malwa', 'maihar', 'singrauli', 'katni', 'khandwa', 'mandsaur', 
    'panna', 'dhar', 'guna', 'gwalior', 'dindori', 'sheopur', 'damoh', 'datia', 'rewa', 'narsinghpur', 
    'sagar', 'shajapur', 'ujjain', 'betul', 'barwani', 'mauganj', 'hoshangabad', 'raisen', 'tikamgarh', 
    'shahdol', 'umaria', 'rajgarh', 'ashoknagar', 'niwari', 'jhabua', 'bhopal', 'morena', 'pandhurna', 'sehore', 
    'bhind', 'harda', 'ratlam']
blocks = ['agar', 'ajaigarh', 'alirajpur', 'alot', 'amarpatan', 'amarpur', 'amarwara', 'ambah', 'amla', 
    'anuppur', 'aron', 'ashoknagar', 'ashta', 'ater', 'athner', 'babai', 'bada malhera', 'badarwas', 'badi', 
    'badnagar', 'badnawar', 'badod', 'badwah', 'badwara', 'bagh', 'bagli', 'bahoriband', 'baihar', 'bajag', 
    'bajna', 'baladi', 'balaghat', 'baldeogarh', 'bamori', 'banda', 'bankhedi', 'barghat', 'bargi', 'barwani', 
    'basoda', 'batiagarh', 'begamganj', 'beohari', 'berasia', 'betul', 'bhabra', 'bhagwanpura', 'bhainsdehi', 
    'bhander', 'bhanpura', 'bhikangaon', 'bhimpur', 'bhind', 'bhitarwar', 'bhopal urban', 'biaora', 'bichhiya', 
    'bichhua', 'bijadandi', 'bijawar', 'bina', 'birsa', 'budni', 'burhanpur', 'burhar', 'buxwaha', 'chachoda', 
    'chanderi', 'chaurai', 'chawarpatha', 'chhaigaon makhan', 'chhapara', 'chhatarpur', 'chhindwara', 'chichli', 
    'chicholi', 'chitrangi', 'dabra', 'dahi', 'damoh', 'datia', 'deori', 'deosar', 'depalpur', 'dewas', 'dhanora', 
    'dhar', 'dharmpuri', 'dhimar kheda', 'dindori', 'gairatganj', 'gandhwani', 'gangev', 'garoth', 'gaurihar', 
    'ghansor', 'ghatia', 'ghatigaon', 'ghoda dongri', 'ghughri', 'gogaon', 'gohad', 'gohparu', 'gotegaon', 'guna', 
    'gunnor', 'gwalior urban', 'gyaraspur', 'hanumana', 'harda', 'harrai', 'harsud', 'hatta', 'hoshangabad', 'ichhawar', 
    'indore', 'indore urban', 'isagarh', 'jabalpur urban', 'jabera', 'jaisinagar', 'jaisinghnagar', 'jaithari', 'jamai', 
    'jaora', 'jatara', 'jaura', 'jawa', 'jawad', 'jhabua', 'jhirniya', 'jirapur', 'jobat', 'kailaras', 'kalapipal', 
    'kannod', 'karahal', 'karanjiya', 'kareli', 'karera', 'karkeli', 'kasrawad', 'katangi', 'katthiwara', 'keolari', 
    'kesla', 'kesli', 'khairlanji', 'khaknar', 'khalwa', 'khandwa', 'khaniyadhana', 'khargone', 'khategaon', 'khchrod', 
    'khilchipur', 'khirkiya', 'khurai', 'kirnapur', 'kolaras', 'kotma', 'kukshi', 'kundam', 'kurai', 'kurwai', 'kusmi', 
    'lahar', 'lakhnadon', 'lalbarra', 'lanji', 'lateri', 'laundi', 'maheshwar', 'mahidpur', 'maihar', 'majhauli', 
    'majhgawan', 'majholi', 'malhargarh', 'malthone', 'manasa', 'manawar', 'mandla', 'mandsaur', 'manpur', 'mauganj', 
    'mawai', 'meghnagar', 'mehgaon', 'menhadwani', 'mhow', 'mohgaon', 'mohkhed', 'moman badodiya', 'morar', 'morena', 
    'multai', 'mungaoli', 'murwara', 'nagod', 'naigarhi', 'nainpur', 'nalchha', 'nalkheda', 'narayanganj', 'narsinghgarh', 
    'narsinghpur', 'narwar', 'nasrullaganj', 'nateran', 'neemuch', 'nisarpur', 'niwali', 'niwari', 'niwas', 'nowgong', 
    'obedullaganj', 'pahadgarh', 'palera', 'pali', 'panagar', 'pandhana', 'pandhurna', 'panna', 'pansemal', 'parasia', 
    'paraswada', 'patan', 'patera', 'patharia', 'pati', 'pawai', 'petlawad', 'phanda', 'pichhore', 'pipariya', 'piploda', 
    'pohari', 'porsa', 'prabhat pattan', 'prithvipur', 'punasa', 'pushparajgarh', 'raghogarh', 'rahatgarh', 'raipur karchuliyan', 
    'rajgarh', 'rajnagar', 'rajpur', 'rama', 'ramnagar', 'rampur naikin', 'rampur-baghelan', 'ranapur', 'ratlam', 'rehli', 'rewa', 
    'rithi', 'ron', 'sabalgarh', 'sagar', 'saikheda', 'sailana', 'samnapur', 'sanchi', 'sanwer', 'sarangpur', 'sardarpur', 'sausar', 
    'segaon', 'sehore', 'sendhwa', 'seondha', 'seoni', 'seoni malwa', 'shahgarh', 'shahnagar', 'shahpur', 'shahpura', 'shahpura', 
    'shajapur', 'sheopur', 'shivpuri', 'shujalpur', 'sidhi', 'sihawal', 'sihora', 'silwani', 'sirmour', 'sironj', 'sitamau', 'sohagpur', 
    'sohagpur', 'sohawal', 'sondwa', 'sonkatch', 'susner', 'tamia', 'tarana', 'tendukheda', 'teonthar', 'thandla', 'thikri', 'tikamgarh', 
    'timarni', 'tirla', 'tonkhurd', 'udaigarh', 'udaipura', 'ujjain', 'umarban', 'unchehara', 'vidisha', 'vijaypur', 'vijayraghavgarh', 
    'waidhan', 'waraseoni']

district_to_blocks = {
    "agar malwa": ["agar", "badod", "nalkheda", "susner"],
    "alirajpur": ["alirajpur", "bhabra", "jobat", "kathiwara", "sodwa", "udaygarh"],
    "anuppur": ["anuppur", "jaithari", "kotma", "pushparajgarh"],
    "ashoknagar": ["ashoknagar", "chanderi", "isagarh", "mungaoli"],
    "balaghat": ["balaghat", "baihar", "birsa", "katangi", "khairlanji", "kirnapur", "lanji", "lalbarra", "paraswada", "waraseoni"],
    "barwani": ["barwani", "anjad", "niwali", "pansemal", "pati", "rajapur", "sendhwa", "thikri"],
    "betul": ["betul", "amla", "athner", "bhainsdehi", "bhimpur", "chicholi", "ghodadongri", "multai", "prabhatpattan", "shahpur"],
    "bhind": ["bhind", "ater", "gohad", "lahar", "mehgaon", "mihona", "ron"],
    "bhopal": ["berasia", "huzur"],
    "burhanpur": ["burhanpur", "khaknar"],
    "chhatarpur": ["chhatarpur", "badamalhera", "bijawar", "buxwaha", "gaurihar", "laundi", "nowgong", "rajnagar"],
    "chhindwara": ["chhindwara", "amarwara", "bichhua", "churai", "harrai", "jamai", "mohkhed", "parasia", "tamia"],
    "damoh": ["damoh", "batiyagarh", "hatta", "jabera", "patharia", "patera", "tendukheda"],
    "datia": ["datia", "bhander", "seondha"],
    "dewas": ["dewas", "bagli", "kannod", "khategaon", "sonkatch", "tonkkhurd"],
    "dhar": ["dhar", "badnawar", "dharampuri", "dhi", "gandhwani", "kukshi", "manawar", "nalchha", "nisarpur", "sardarpur", "tirla", "bagh", "umarban"],
    "dindori": ["dindori", "amarpur", "bajag", "karanjiya", "mehadwani", "samnapur", "shahpura"],
    "guna": ["guna", "aaron", "bamori", "chachoda", "raghogarh"],
    "gwalior": ["ghatigaon", "bhitarwar", "dabra", "murar"],
    "harda": ["harda", "khirkiya", "timarni"],
    "hoshangabad": ["hoshangabad", "babaichichli", "bankhedi", "kesla", "pipariya", "seonimalwa", "sohagpur"],
    "indore": ["indore","indore urban" "depalpur", "mhow", "sanwer"],
    "jabalpur": ["kundam", "bargi", "majholi", "panagar", "patan", "shahpura", "sihora"],
    "jhabua": ["jhabua", "meghnagar", "petlawad", "rama", "ranapur", "thandla"],
    "katni": ["murwara", "badwara", "bahoriband", "dheemerkheda", "reethi", "vijayraghavgarh"],
    "khandwa (east nimar)": ["khandwa", "chhaigaonmakhan", "harsood", "khalwa", "pandhana", "punasa", "baldi"],
    "khargone (west nimar)": ["khargone", "bhagwanpura", "bhikangaon", "gogaon", "jhiranya", "kasrawad", "maheshwar", "segaon", "barwah"],
    "maihar": ["maihar", "amarpatan"],
    "mandla": ["mandla", "bichiya", "ghughari", "gwalan (bamhani)", "mawai", "mohgaon", "nainpur", "narayanganj", "niwas"],
    "mandsaur": ["mandsaur", "bhanpura", "dalodafatehgarh", "garoth", "malhargarh", "sitamau"],
    "mauganj": ["mauganj", "hanumana", "naigarhi"],
    "morena": ["morena", "ambah", "jora", "kailaras", "porsa", "sabalgarh"],
    "narsinghpur": ["narsinghpur", "babai chichli", "gotegaon", "kareli", "sainkheda", "chawerpatha"],
    "neemuch": ["neemuch", "jawad", "manasa"],
    "niwari": ["niwari", "prithvipur", "orchha"],
    "panna": ["panna", "ajaigarh", "gunnor", "pawai", "shahpur"],
    "pandhurna": ["pandhurna", "saunsar"],
    "raisen": ["raisen", "badigaon", "bareli", "begumganj", "gairatganj", "obedullaganj", "sanchi", "silwani", "udaipura"],
    "rajgarh": ["rajgarh", "biaora", "jirapur", "khilchipur", "narsingarh", "sarangpur"],
    "ratlam": ["ratlam", "alote", "bajna", "jaora", "piploda", "sailana"],
    "rewa": ["raipur-karchuliyan", "gangaw", "jawa", "sirmour", "teonthar"],
    "sagar": ["sagar", "banda", "bina", "deori", "jesinagar", "keshai", "khurai", "malkuan", "rahatgarh", "shahgarh"],
    "satna": ["majhgawan", "nagod", "ramnagar", "rampur-baghelan", "sohawal", "uchehra"],
    "sehore": ["sehore", "ashta", "budhni", "ichhawar", "nasrullaganj"],
    "seoni": ["seoni", "barghat", "chhapara", "dhanora", "ghansor", "keolari", "kurai", "lakhanadon"],
    "shahdol": ["sohagpur", "beohari", "burhar", "jaisinghnagar", "gohparu"],
    "shajapur": ["shajapur", "kalapipal", "mohanbadodiya", "shujalpur"],
    "sheopur": ["sheopur", "karahal", "vijaipur"],
    "shivpuri": ["shivpuri", "badarwas", "karera", "khaniadhana", "kolaras", "narwar", "pichhore", "pohari"],
    "sidhi": ["sidhi", "kusmi", "majhauli", "rampur naikin", "sihawal"],
    "singrauli": ["baidhan", "chintrangi", "deosar"],
    "tikamgarh": ["tikamgarh", "baldeogarh", "jatara", "palera"],
    "ujjain": ["ghatiya", "badnagar", "khachrod", "mahidpur", "tarana"],
    "umaria": ["bandhavgarh", "karkeli(manpur)", "pali"],
    "vidisha": ["vidisha", "basoda", "gyaraspur", "kurwai", "lateri", "nateran", "sironj"]
}